### ISSUE TITLE
The results of general properties of the molecules

### ISSUE THREAD

**Issue by ALEEEHU** [pengxingang/Pocket2Mol#11]
The paper states the LogP of the Pocket2Mol is **1.586**±1.82. 
However, my reproduction result is **0.146**±1.06. 
I'm wondering why the mean of the LogP is so different.

**Comment by pengxingang** [comment]
Thanks for your interest in the work. There might be many reasons that LogP is different. First, the generation is random and the generated molecules are different for the different runs. It is not clear how the values of LogP are sensitive to such randomness of the sampling. Second, the parameters of sampling can also have an influence on the generation and the LogP might be sensitive to them. Third, the released test dataset is slightly different from the one used in the paper because we further adapted the test set for easy usage. And the codes were also slightly modified after publication. All these changes might have a great impact on LogP.

**Comment by ALEEEHU** [comment]
I see. Thanks for your prompt reply！
