### ISSUE TITLE
ERROR: Could not sanitize molecule ending on line 77

### ISSUE THREAD

**Issue by xiaoxiannv999** [pengxingang/Pocket2Mol#12]
[16:19:54] Explicit valence for atom # 19 C, 5, is greater than permitted
[16:19:54] ERROR: Could not sanitize molecule ending on line 77
[16:19:54] ERROR: Explicit valence for atom # 19 C, 5, is greater than permitted
Skipping (431) BRD4_HUMAN_42_168_0/5cs8_A_rec_4o7f_2rq_lig_tt_docked_6.sdf

What is the reason for this error? (Please forgive me for my first exposure to this direction)

**Comment by pengxingang** [comment]
I guess these messages appeared when you first ran the training or sampling script. At the first run, it will automatically preprocess the data. It will read the raw sdf files and process them using rdkit package. But some sdf files cannot be read by the rdkit package because some minor cases cannot be handled automatically. So we just skip these molecules. It does not influence the subsequent training or sampling.
